#!/usr/bin/env node
// Regenerates index.html from whatever build folders exist in builds/.
// Run after adding or removing a build:  node scripts/generate-index.mjs

import { readdirSync, readFileSync, statSync, existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const buildsDir = join(root, "builds");

// Project name, author, and description live in config.json so the copy can be
// edited without touching this template.
const config = JSON.parse(readFileSync(join(root, "config.json"), "utf8"));

for (const field of ["name", "author"]) {
  if (!config[field]?.trim()) {
    console.error(`config.json is missing a non-empty "${field}"`);
    process.exit(1);
  }
}

const escapeHtml = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

const projectName = escapeHtml(config.name);
const projectAuthor = escapeHtml(config.author);
// description is optional — omit it from config.json and the paragraph is left out.
const projectDescription = config.description?.trim()
  ? escapeHtml(config.description.trim())
  : null;

const isDate = (name) => /^\d{4}-\d{2}-\d{2}$/.test(name);

const builds = readdirSync(buildsDir)
  .filter((name) => isDate(name) && statSync(join(buildsDir, name)).isDirectory())
  .sort()
  .reverse();

if (builds.length === 0) {
  console.error("No dated build folders found in builds/");
  process.exit(1);
}

const missing = builds.filter((name) => !existsSync(join(buildsDir, name, "index.html")));
if (missing.length > 0) {
  console.error(`Skipping builds with no index.html: ${missing.join(", ")}`);
}

const listed = builds.filter((name) => !missing.includes(name));

const longDate = (iso) =>
  new Date(`${iso}T00:00:00Z`).toLocaleDateString("en-CA", {
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  });

const items = listed
  .map(
    (name) => `        <li>
          <a href="builds/${name}/index.html">
            <span class="date">${longDate(name)}</span>
            <span class="iso">${name}</span>
          </a>
        </li>`
  )
  .join("\n");

const first = listed[listed.length - 1];
const last = listed[0];

const html = `<!DOCTYPE html>
<!-- Generated by scripts/generate-index.mjs — edit that file, not this one. -->
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${projectName} | Materializing Design</title>
  <meta name="description"
    content="${projectName} by ${projectAuthor} — an archive of ${listed.length} dated builds, ${first} to ${last}.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700&family=JetBrains+Mono:wght@400;600;700&display=swap">
  <style>
    /* Palette and type mirror the main site's theme engine (globals.css / layout.tsx).
       If a token changes there, change it here too. */
    :root {
      --coral: #E95F58;
      --ink: #2C2C2A;
      --white: #FFFFFF;
      --parchment: #F1EFE8;
      --stone: #8A8A8A;
      --background: #EEE;
      --font-heading: "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
      --font-body: "Archivo", system-ui, sans-serif;
    }

    * { box-sizing: border-box; }

    html { scroll-behavior: smooth; }

    body {
      margin: 0;
      background-color: var(--background);
      color: var(--ink);
      font-family: var(--font-body);
      -webkit-font-smoothing: antialiased;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }

    a { text-decoration: none; }

    /* ── Header ─────────────────────────────────────────────────────────────── */
    .site-header { width: 100%; padding: 1.5rem 1.5rem 1rem; }

    .site-header .row {
      display: flex;
      flex-wrap: wrap;
      align-items: center;
      justify-content: space-between;
      gap: 0.75rem 1rem;
    }

    .site-header img { width: 240px; max-width: min(240px, 60vw); height: auto; }

    .repo-name {
      font-family: var(--font-heading);
      font-weight: 700;
      font-size: 0.875rem;
      color: var(--ink);
      transition: color 0.15s;
    }

    a.repo-name:hover { color: var(--coral); }

    /* ── Main ───────────────────────────────────────────────────────────────── */
    main {
      flex: 1;
      width: 100%;
      max-width: 72rem;
      margin: 0 auto;
      padding: 2.5rem 1.5rem;
    }

    h1 {
      font-family: var(--font-heading);
      font-weight: 700;
      font-size: 1.875rem;
      color: var(--ink);
      margin: 0 0 0.5rem;
    }

    .subtitle {
      font-family: var(--font-heading);
      font-size: 0.875rem;
      color: var(--stone);
      margin: 0 0 1rem;
    }

    .lede {
      font-size: 0.9375rem;
      color: var(--stone);
      max-width: 44rem;
      line-height: 1.7;
      margin: 0 0 2.5rem;
    }

    /* The top margin only takes effect when there's no description above to collapse
       against, so the list keeps its spacing either way. */
    .build-count {
      font-family: var(--font-heading);
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: var(--stone);
      margin: 2.5rem 0 0.75rem;
    }

    /* ── Build list ─────────────────────────────────────────────────────────── */
    ul.builds {
      list-style: none;
      margin: 0;
      padding: 0;
      max-width: 44rem;
      border-top: 1px solid rgba(138, 138, 138, 0.2);
    }

    ul.builds li { border-bottom: 1px solid rgba(138, 138, 138, 0.2); }

    ul.builds a {
      display: flex;
      align-items: baseline;
      justify-content: space-between;
      gap: 1rem;
      padding: 0.75rem 0.25rem;
      color: var(--ink);
      transition: color 0.15s, background-color 0.15s;
    }

    ul.builds a:hover,
    ul.builds a:focus-visible { color: var(--coral); background: rgba(255, 255, 255, 0.6); }

    ul.builds a:focus-visible { outline: 2px solid var(--coral); outline-offset: -2px; }

    .date { font-size: 0.9375rem; }

    ul.builds a:hover .date { text-decoration: underline; }

    .iso {
      flex-shrink: 0;
      font-family: var(--font-heading);
      font-size: 0.75rem;
      color: var(--stone);
    }

    /* ── Footer ─────────────────────────────────────────────────────────────── */
    .site-footer {
      width: 100%;
      border-top: 1px solid rgba(138, 138, 138, 0.2);
      margin-top: 5rem;
      padding: 2.5rem 1.5rem;
    }

    .site-footer .inner {
      max-width: 72rem;
      margin: 0 auto;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      align-items: flex-start;
      gap: 2rem;
    }

    @media (min-width: 768px) {
      .site-header, main, .site-footer { padding-left: 2.5rem; padding-right: 2.5rem; }
      .site-footer .inner { flex-direction: row; align-items: center; }
    }

    .foot-links { display: flex; gap: 2.5rem; font-size: 0.875rem; }

    .foot-col { display: flex; flex-direction: column; gap: 0.375rem; }

    .foot-col p {
      font-family: var(--font-heading);
      font-weight: 700;
      color: var(--ink);
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      margin: 0 0 0.25rem;
    }

    .foot-col a { color: var(--stone); transition: color 0.15s; }

    .foot-col a:hover { color: var(--coral); }

    .foot-logos {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      gap: 1.5rem;
      min-width: 0;
    }

    /* Wraps as well as rows: side by side these two are ~565px, which overflows a
       768px viewport once the link columns sit beside them. */
    @media (min-width: 640px) {
      .foot-logos { flex-direction: row; flex-wrap: wrap; align-items: center; }
    }

    .foot-logos img { height: auto; object-fit: contain; max-width: 100%; }

    .foot-logos .sshrc { width: 400px; }

    .foot-logos .concordia { width: 140px; }
  </style>
</head>

<body>
  <header class="site-header">
    <div class="row">
      <a href="https://materializing.design/">
        <img src="assets/MD_logo.svg" alt="Materializing Design">
      </a>
      <a class="repo-name" href="https://github.com/Materializing-Design/Pudding">Pudding</a>
    </div>
  </header>

  <main>
    <h1>${projectName}</h1>
    <p class="subtitle">${projectAuthor}</p>
${projectDescription ? `    <p class="lede">${projectDescription}</p>\n` : ""}
    <p class="build-count">${listed.length} builds &middot; ${first} to ${last}</p>

    <ul class="builds">
${items}
    </ul>
  </main>

  <footer class="site-footer">
    <div class="inner">
      <div class="foot-links">
        <div class="foot-col">
          <p>MDM</p>
          <a href="https://materializing.design/mdm">Method</a>
          <a href="https://materializing.design/design-archive">Archive</a>
          <a href="https://materializing.design/analyses">Analyses</a>
          <a href="https://materializing.design/guides-and-tools">Guides</a>
        </div>
        <div class="foot-col">
          <p>Connect</p>
          <a href="mailto:hello@materializing.design">Email</a>
          <a href="https://github.com/Materializing-Design" target="_blank" rel="noreferrer">GitHub</a>
          <a href="https://materializing.design/about">About</a>
        </div>
      </div>
      <div class="foot-logos">
        <img class="sshrc" src="assets/SSHRC_logo.svg"
          alt="Social Sciences and Humanities Research Council of Canada">
        <img class="concordia" src="assets/Concordia_logo.svg" alt="Concordia University">
      </div>
    </div>
  </footer>
</body>

</html>
`;

writeFileSync(join(root, "index.html"), html);
console.log(`Wrote index.html with ${listed.length} builds (${first} → ${last}).`);
